### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by islamsamy214** [primefaces/sakai-vue#21]
I just cloned the repo and trying to run ``npm install`` and it gives me this:

```
/usr/share/nodejs/npm/lib/cli.js:48
    throw err
    ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.<anonymous> (/usr/share/nodejs/depd/index.js:23:24)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/share/nodejs/npm/node_modules/agentkeepalive/lib/agent.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1218:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v18.13.0
```

**Comment by islamsamy214** [comment]
I think it was my issue, sounds maybe saily, but I just closed and opened my terminal LOL
