### ISSUE TITLE
Vue I18n breaks the UI

### ISSUE THREAD

**Issue by GuanglinDu** [primefaces/sakai-vue#57]
Many Thanks for this great template and the extremely elegant PrimeVue UI components you created and open-sourced to the world selflessly.

**(1/3)** Followed the [Vue I18n](https://vue-i18n.intlify.dev/guide/introduction.html) to install the plug-in:
   `npm install vue-i18n@10`

**(2/3)** Modified main.js as follows:
```
import { createApp } from 'vue';
import { createI18n } from 'vue-i18n';
import App from './App.vue';
import router from './router'; // equivalent to './router/index.js'

import Aura from '@primevue/themes/aura';
import PrimeVue from 'primevue/config';
import ConfirmationService from 'primevue/confirmationservice';
import ToastService from 'primevue/toastservice';

import '@/assets/styles.scss';
import '@/assets/tailwind.css';

const i18n = createI18n({
    locale: 'en',
    fallbackLocale: 'en',
    messages: {
        en: {
            message: {
                hello: 'hello world'
            }
        },
        cn: {
            message: {
                hello: '世界，你好！'
            }
        }
    }
});

const app = createApp(App);

app.use(router);
app.use(PrimeVue, {
    theme: {
        preset: Aura,
        options: {
            darkModeSelector: '.app-dark'
        }
    }
});
app.use(ToastService);
app.use(ConfirmationService);

// app.use(i18n); // breaks the UI
app.mount('#app');

```
**(3/3)** The second code line from bottom up breaks the UI (empty) with error message in the browser console:
```
runtime-core.esm-bundler.js:51  [Vue warn]: Failed to resolve component: sodipodi:namedview
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <AppTopbar> 
  at <AppLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn$1 @ runtime-core.esm-bundler.js:51
Show 1 more frame
Show less
runtime-core.esm-bundler.js:51  [Vue warn]: Cannot mutate <script setup> binding "$t" from Options API. 
  at <AppConfigurator> 
  at <AppTopbar> 
  at <AppLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn$1 @ runtime-core.esm-bundler.js:51
Show 1 more frame
Show less
runtime-core.esm-bundler.js:51  [Vue warn]: Unhandled error during execution of beforeCreate hook 
  at <AppConfigurator> 
  at <AppTopbar> 
  at <AppLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn$1 @ runtime-core.esm-bundler.js:51
Show 1 more frame
Show less
runtime-core.esm-bundler.js:51  [Vue warn]: Unhandled error during execution of component update 
  at <RouterView> 
  at <App>
warn$1 @ runtime-core.esm-bundler.js:51
Show 1 more frame
Show less
vue-i18n.mjs:1562  Uncaught (in promise) TypeError: 'set' on proxy: trap returned falsish for property '$t'
    at Proxy.beforeCreate (vue-i18n.mjs:1562:18)
    at callWithErrorHandling (runtime-core.esm-bundler.js:202:33)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:209:17)
    at callHook (runtime-core.esm-bundler.js:2343:3)
    at applyOptions (runtime-core.esm-bundler.js:2122:5)
    at finishComponentSetup (runtime-core.esm-bundler.js:7813:7)
    at handleSetupResult (runtime-core.esm-bundler.js:7764:3)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7733:7)
    at setupComponent (runtime-core.esm-bundler.js:7665:36)
    at mountComponent (runtime-core.esm-bundler.js:4873:7)
```

**Comment by GuanglinDu** [comment]
Fixed by adding a property `legacy: false` in function call createI18n. The complete main.js is as follows:
```
import { createApp } from 'vue';
import { createI18n } from 'vue-i18n';
import App from './App.vue';
import router from './router'; // equivalent to './router/index.js'

import Aura from '@primevue/themes/aura';
import PrimeVue from 'primevue/config';
import ConfirmationService from 'primevue/confirmationservice';
import ToastService from 'primevue/toastservice';

import '@/assets/styles.scss';
import '@/assets/tailwind.css';

// Must set legacy `false` to use the Composition API
const i18n = createI18n({
    legacy: false,
    global: true,
    locale: 'en',
    fallbackLocale: 'en',
    messages: {
        en: {
            message: {
                hello: 'hello world',
                software_creator: 'XX Co., Ltd.'
            }
        },
        cn: {
            message: {
                hello: '世界，你好',
                software_creator: 'XX公司'
            }
        }
    }
});

const app = createApp(App);

app.use(router);
app.use(PrimeVue, {
    theme: {
        preset: Aura,
        options: {
            darkModeSelector: '.app-dark'
        }
    }
});
app.use(ToastService);
app.use(ConfirmationService);

app.use(i18n);
app.mount('#app');

```

**Comment by GuanglinDu** [comment]
A better solution: separating the language files from main.js.

**(1/3) main.js**
```
import CN from '@/locales/cn.json';
import EN from '@/locales/en.json';
import { createApp } from 'vue';
import { createI18n } from 'vue-i18n';

import App from './App.vue';
import router from './router'; // equivalent to './router/index.js'

import Aura from '@primevue/themes/aura';
import PrimeVue from 'primevue/config';
import ConfirmationService from 'primevue/confirmationservice';
import ToastService from 'primevue/toastservice';

import '@/assets/styles.scss';
import '@/assets/tailwind.css';

// Must set legacy `false` to use the Composition API
const i18n = createI18n({
    legacy: false,
    global: true,
    locale: 'CN',
    fallbackLocale: 'EN',
    messages: { EN: EN, CN: CN }
});

const app = createApp(App);

app.use(router);
app.use(PrimeVue, {
    theme: {
        preset: Aura,
        options: {
            darkModeSelector: '.app-dark'
        }
    }
});
app.use(ToastService);
app.use(ConfirmationService);

app.use(i18n);
app.mount('#app');
```

**(2/3) @/locales/en.json (i.e., src/locales/en.json)**
```
{
    "_comment01": "This is the language package for English",
    "software_creator": "XX Co., Ltd.",
    "dashboard": "Dashboard",
    "general_evaluation_system": "General Evaluation System"
}
```

**(3/3) In your components (*.vue files)**
```
<script setup></script>

<template>
    <div class="layout-footer">
       Lab footer by
        <a href="#" target="_blank" rel="noopener noreferrer" class="text-primary font-bold hover:underline">
            {{ $t('software_creator') }}
        </a>
    </div>
</template>
```

**Comment by GuanglinDu** [comment]
This issue has been self-healed!
